/** Ids for generate-control prompt bodies. Values only — bodies live in the registry. */

export enum StorytellerPromptRegistryId {
  CorkBoardGenerateBeats = 'cork-board-generate-beats',
  CorkBoardGenerateNextBeat = 'cork-board-generate-next-beat',
  WorldDescriptionRegen = 'world-description-regen',
  BibleInspirationGenerate = 'bible-inspiration-generate',
  BibleRoadmapGenerate = 'bible-roadmap-generate',
  BibleFactionsGenerate = 'bible-factions-generate',
  BibleWorldRulesGenerate = 'bible-world-rules-generate',
  BiblePlotTwistsGenerate = 'bible-plot-twists-generate',
  BibleSoundtracksGenerate = 'bible-soundtracks-generate',
  BibleItemsGenerate = 'bible-items-generate',
  BibleEventsGenerate = 'bible-events-generate',
  ScriptEditorExpand = 'script-editor-expand',
  ScriptEditorCondense = 'script-editor-condense',
  ScriptEditorRewrite = 'script-editor-rewrite',
  ScriptEditorSystem = 'script-editor-system',
  GenerateEpisodeDescriptionUser = 'generate-episode-description-user',
  GenerateEpisodePremiseAgent = 'generate-episode-premise-agent',
  GenerateRoadmapUser = 'generate-roadmap-user',
  GenerateRoadmapAgent = 'generate-roadmap-agent',
  RegeneratePremiseSectionUserPrefix = 'regenerate-premise-section-user-prefix',
  RegeneratePremiseSectionUserSuffix = 'regenerate-premise-section-user-suffix',
  RegeneratePremiseSectionAgentPrefix = 'regenerate-premise-section-agent-prefix',
  RegeneratePremiseSectionAgentMid = 'regenerate-premise-section-agent-mid',
  RegeneratePremiseSectionAgentSuffix = 'regenerate-premise-section-agent-suffix',
  CharacterGenerateMissing = 'character-generate-missing',
}
