'use client'

import { useEffect } from 'react'
import { AssetExporterSidebar } from '@/domains/3d-asset-exporter/components/AssetExporterSidebar'
import { useWorldStore } from '@/domains/world-building-toolkit/store/useWorldStore'
import { AssetEditor } from '@/domains/3d-asset-exporter/components/AssetEditor'
import { ThreeDPanel } from '@/domains/3d-asset-exporter/components/ThreeDPanel'
import { Box } from 'lucide-react'
import { useProjectFromUrl } from '@/hooks/useProjectFromUrl'
import { TOUR_STEP_IDS } from '@/lib/tour-constants'

export default function AssetExporterPage() {
  // Load project from URL
  useProjectFromUrl()

  const currentProject = useWorldStore(state => state.currentProject)
  const assets = useWorldStore(state => state.assets)
  const previewAssetId = useWorldStore(state => state.previewAssetId)
  const setPreviewAssetId = useWorldStore(state => state.setPreviewAssetId)

  // Clear selected asset when navigating away from this page
  useEffect(() => {
    return () => {
      setPreviewAssetId(null)
    }
  }, [setPreviewAssetId])

  const selectedAsset = assets.find(a => a.id === previewAssetId)

  return (
    <div className="flex h-full w-full overflow-hidden bg-background text-foreground">
      <div id={TOUR_STEP_IDS.EXPORTED_ASSETS_LIST}>
        <AssetExporterSidebar />
      </div>
      <div className="flex-1 relative flex flex-col bg-muted/10 overflow-hidden">
        {selectedAsset && currentProject ? (
          <div className="grid grid-cols-2 gap-6 h-full">
            {/* 2D Asset View / Editor */}
            <div id={TOUR_STEP_IDS.ASSET_EDITOR_PANEL}>
              <AssetEditor
                key={`editor-${selectedAsset.id}`} // Force remount on asset change
                assetId={selectedAsset.id}
                imageUrl={`/projects/${currentProject.id}/assets/${selectedAsset.image_filename}`}
                hasModel={!!selectedAsset.model_filename}
                imageFilename={selectedAsset.image_filename}
                isPlaceholderImage={
                  (selectedAsset.metadata as any)?.autoGeneratedThumbnail === true
                }
              />
            </div>

            {/* 3D Preview Panel */}
            <ThreeDPanel
              key={`3d-${selectedAsset.id}`}
              assetId={selectedAsset.id}
              imageUrl={`/projects/${currentProject.id}/assets/${selectedAsset.image_filename}`}
              initialModelUrl={
                selectedAsset.model_filename
                  ? selectedAsset.model_filename.startsWith('http://') ||
                    selectedAsset.model_filename.startsWith('https://')
                    ? selectedAsset.model_filename // External URL - use as-is
                    : `/projects/${currentProject.id}/assets/${selectedAsset.model_filename}` // Local file
                  : undefined
              }
            />
          </div>
        ) : (
          <div className="flex-1 flex items-center justify-center">
            <div className="text-center space-y-4 max-w-md">
              <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto">
                <Box size={32} className="text-muted-foreground opacity-50" />
              </div>
              <h2 className="text-2xl font-bold text-muted-foreground">No Asset Selected</h2>
              <p className="text-muted-foreground">
                Select an exported asset from the sidebar to view details and generate 3D models.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
