'use client'

import { useEffect } from 'react'
import { AssetExporterSidebar } from '@/domains/3d-asset-exporter/components/AssetExporterSidebar'
import { useWorldStore } from '@/domains/world-building-toolkit/store/useWorldStore'
import { AssetEditor } from '@/domains/3d-asset-exporter/components/AssetEditor'
import { ThreeDPanel } from '@/domains/3d-asset-exporter/components/ThreeDPanel'
import { Image as ImageIcon, Box } from 'lucide-react'
import { useProjectFromUrl } from '@/hooks/useProjectFromUrl'
import { TOUR_STEP_IDS } from '@/lib/tour-constants'

export default function AssetExporterPage() {
  // Load project from URL
  useProjectFromUrl()

  const currentProject = useWorldStore(state => state.currentProject)
  const assets = useWorldStore(state => state.assets)
  const previewAssetId = useWorldStore(state => state.previewAssetId)
  const setPreviewAssetId = useWorldStore(state => state.setPreviewAssetId)

  // Clear selected asset when navigating away from this page
  useEffect(() => {
    return () => {
      setPreviewAssetId(null)
    }
  }, [setPreviewAssetId])

  const selectedAsset = assets.find(a => a.id === previewAssetId)

  return (
    <div className="flex h-full w-full overflow-hidden bg-background text-foreground">
      <div id={TOUR_STEP_IDS.EXPORTED_ASSETS_LIST}>
        <AssetExporterSidebar />
      </div>
      <div className="flex-1 relative flex flex-col bg-muted/10 overflow-hidden">
        {/* Always render editor panel container for tour selector */}
        <div className="grid grid-cols-2 gap-6 h-full">
          {/* 2D Asset View / Editor */}
          <div id={TOUR_STEP_IDS.ASSET_EDITOR_PANEL} className="">
            {selectedAsset && currentProject ? (
              <AssetEditor
                key={`editor-${selectedAsset.id}`} // Force remount on asset change
                assetId={selectedAsset.id}
                imageUrl={selectedAsset.image_filename.startsWith('http') ? selectedAsset.image_filename : `/projects/${currentProject.id}/assets/${selectedAsset.image_filename}`}
                hasModel={!!selectedAsset.model_filename}
                imageFilename={selectedAsset.image_filename}
                isPlaceholderImage={
                  (selectedAsset.metadata as any)?.autoGeneratedThumbnail === true
                }
              />
            ) : (
              <div className="flex flex-col h-full bg-card border border-border rounded-lg overflow-hidden shadow-sm">
                <div className="p-3 border-b border-border flex items-center justify-between bg-muted/30">
                  <div className="flex items-center gap-2">
                    <ImageIcon size={16} className="text-muted-foreground" />
                    <h3 className="font-medium text-sm">2D Editor</h3>
                  </div>
                </div>
                <div className="flex-1 bg-[#1a1a1a] relative overflow-hidden flex items-center justify-center">
                  <div
                    className="absolute inset-0 opacity-[0.03] pointer-events-none"
                    style={{
                      backgroundImage: 'linear-gradient(45deg, #808080 25%, transparent 25%), linear-gradient(-45deg, #808080 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #808080 75%), linear-gradient(-45deg, transparent 75%, #808080 75%)',
                      backgroundSize: '20px 20px',
                      backgroundPosition: '0 0, 0 10px, 10px -10px, -10px 0px',
                    }}
                  />
                  <div
                    className="
                      relative z-10 w-full max-w-md mx-4 border-2 border-dashed rounded-xl p-8 transition-all
                      border-muted-foreground/30 bg-background/5
                    "
                  >
                    <div className="flex flex-col items-center gap-4 text-center">
                      <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center">
                        <ImageIcon size={32} className="text-muted-foreground opacity-50" />
                      </div>
                      <div>
                        <h4 className="font-medium text-foreground mb-1">No Asset Selected</h4>
                        <p className="text-sm text-muted-foreground mb-1">
                          Select an asset from the sidebar to start editing and generating 3D models.
                        </p>
                        <p className="text-xs text-muted-foreground mt-1">
                          💡 Tip: Upload images or export tiles from World Gen to get started
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* 3D Preview Panel - always render for tour selector */}
          {currentProject ? (
            <ThreeDPanel
              key={`3d-${selectedAsset?.id || 'empty'}`}
              assetId={selectedAsset?.id || ''}
              imageUrl={selectedAsset ? (selectedAsset.image_filename.startsWith('http') ? selectedAsset.image_filename : `/projects/${currentProject.id}/assets/${selectedAsset.image_filename}`) : ''}
              initialModelUrl={
                selectedAsset?.model_filename
                  ? selectedAsset.model_filename.startsWith('http://') ||
                    selectedAsset.model_filename.startsWith('https://')
                    ? selectedAsset.model_filename // External URL - use as-is
                    : `/projects/${currentProject.id}/assets/${selectedAsset.model_filename}` // Local file
                  : undefined
              }
            />
          ) : (
            <div id={TOUR_STEP_IDS.ASSET_3D_PREVIEW} className="flex items-center justify-center bg-[#1a1a1a]">
              <div className="text-center space-y-4 max-w-md px-6">
                <div className="w-20 h-20 bg-gradient-to-br from-primary/20 to-purple-500/20 rounded-full flex items-center justify-center mx-auto border border-primary/20">
                  <Box size={40} className="text-primary/60" />
                </div>
                <div className="space-y-2">
                  <h2 className="text-2xl font-bold text-foreground">No Project Loaded</h2>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    Please select a project to view the 3D preview panel.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
