import { fn } from 'storybook/test'

export const noopClick = fn()
export const noopChange = fn()
export const noopPick = fn()
export const noopClose = fn()
export const noopConfirm = fn()
export const noopOpenChange = fn()
export const noopSelect = fn()
export const noopRemove = fn()
export const noopRetry = fn()
export const noopCancel = fn()
export const noopDownload = fn()
export const noopNext = fn()
export const noopPrev = fn()
export const noopSuggest = fn()
export const noopSuggestPick = fn()
export const noopToggle = fn()
export const noopAccept = fn()
export const noopReject = fn()
