'use client'

import { useEffect, type ReactNode } from 'react'
import { Image as ImageIcon, Box } from 'lucide-react'
import { TOUR_STEP_IDS } from '@/shared/tours/tour-constants'
import { recordFromJson } from '@/shared/data/json-guards'
import { resolveProjectAssetUrl } from '@/shared/workspace/io/project-assets-api'
import { AssetEditor } from './AssetEditor'
import { AssetExporterSidebar, type AssetExporterAssetsBind } from './AssetExporterSidebar'
import { ThreeDPanel } from './ThreeDPanel'

export interface AssetExporterLayoutAsset {
  id: string
  image_filename: string
  model_filename?: string | null
  metadata: Record<string, unknown>
}

export interface AssetExporterLayoutProps {
  currentProject: { id: string } | null
  assets: AssetExporterLayoutAsset[]
  previewAssetId: string | null
  setPreviewAssetId: (id: string | null) => void
  updateAsset: (id: string, updates: Partial<AssetExporterLayoutAsset>) => void
  fetchAssets: () => Promise<void>
  user: unknown
  assetsBind: AssetExporterAssetsBind
  settingsDialog: ReactNode
}

export function AssetExporterLayout({
  currentProject,
  assets,
  previewAssetId,
  setPreviewAssetId,
  updateAsset,
  fetchAssets,
  user,
  assetsBind,
  settingsDialog,
}: AssetExporterLayoutProps) {
  useEffect(() => {
    return () => {
      setPreviewAssetId(null)
    }
  }, [setPreviewAssetId])

  const selectedAsset = assets.find(asset => asset.id === previewAssetId)

  return (
    <div className="flex h-full w-full overflow-hidden bg-background text-foreground">
      <div id={TOUR_STEP_IDS.EXPORTED_ASSETS_LIST}>
        <AssetExporterSidebar
          currentProject={currentProject}
          assetsBind={assetsBind}
          settingsDialog={settingsDialog}
        />
      </div>
      <div className="flex-1 relative flex flex-col bg-muted/10 overflow-hidden">
        <div className="grid grid-cols-2 gap-6 h-full">
          <div id={TOUR_STEP_IDS.ASSET_EDITOR_PANEL} className="">
            {selectedAsset && currentProject ? (
              <AssetEditor
                key={`editor-${selectedAsset.id}`}
                assetId={selectedAsset.id}
                projectId={currentProject.id}
                imageUrl={resolveProjectAssetUrl(currentProject.id, selectedAsset.image_filename)}
                hasModel={!!selectedAsset.model_filename}
                imageFilename={selectedAsset.image_filename}
                isPlaceholderImage={
                  recordFromJson(selectedAsset.metadata).autoGeneratedThumbnail === true
                }
                onUpdateAsset={updateAsset}
                onFetchAssets={fetchAssets}
              />
            ) : (
              <div className="flex flex-col h-full bg-card border border-border rounded-lg overflow-hidden shadow-sm">
                <div className="p-3 border-b border-border flex items-center justify-between bg-muted/30">
                  <div className="flex items-center gap-2">
                    <ImageIcon size={16} className="text-muted-foreground" />
                    <h3 className="font-medium text-sm">2D Editor</h3>
                  </div>
                </div>
                <div className="flex-1 bg-[#1a1a1a] relative overflow-hidden flex items-center justify-center">
                  <div
                    className="absolute inset-0 opacity-[0.03] pointer-events-none"
                    style={{
                      backgroundImage:
                        'linear-gradient(45deg, #808080 25%, transparent 25%), linear-gradient(-45deg, #808080 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #808080 75%), linear-gradient(-45deg, transparent 75%, #808080 75%)',
                      backgroundSize: '20px 20px',
                      backgroundPosition: '0 0, 0 10px, 10px -10px, -10px 0px',
                    }}
                  />
                  <div
                    className="
                      relative z-10 w-full max-w-md mx-4 border-2 border-dashed rounded-xl p-8 transition-all
                      border-muted-foreground/30 bg-background/5
                    "
                  >
                    <div className="flex flex-col items-center gap-4 text-center">
                      <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center">
                        <ImageIcon size={32} className="text-muted-foreground opacity-50" />
                      </div>
                      <div>
                        <h4 className="font-medium text-foreground mb-1">No Asset Selected</h4>
                        <p className="text-sm text-muted-foreground mb-1">
                          Select an asset from the sidebar to start editing and generating 3D models.
                        </p>
                        <p className="text-xs text-muted-foreground mt-1">
                          💡 Tip: Upload images or export tiles from World Gen to get started
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {currentProject ? (
            <ThreeDPanel
              key={`3d-${selectedAsset?.id || 'empty'}`}
              assetId={selectedAsset?.id || ''}
              imageUrl={
                selectedAsset
                  ? resolveProjectAssetUrl(currentProject.id, selectedAsset.image_filename)
                  : ''
              }
              initialModelUrl={
                selectedAsset?.model_filename
                  ? resolveProjectAssetUrl(currentProject.id, selectedAsset.model_filename)
                  : undefined
              }
              projectId={currentProject.id}
              user={user}
              onUpdateAsset={updateAsset}
            />
          ) : (
            <div id={TOUR_STEP_IDS.ASSET_3D_PREVIEW} className="flex items-center justify-center bg-[#1a1a1a]">
              <div className="text-center space-y-4 max-w-md px-6">
                <div className="w-20 h-20 bg-gradient-to-br from-primary/20 to-purple-500/20 rounded-full flex items-center justify-center mx-auto border border-primary/20">
                  <Box size={40} className="text-primary/60" />
                </div>
                <div className="space-y-2">
                  <h2 className="text-2xl font-bold text-foreground">No Project Loaded</h2>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    Please select a project to view the 3D preview panel.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
