export const FAL_SAM_CALL_LOG_PREFIX = '[FalClient] Calling SAM-3 with:'
export const FAL_NONE_PLACEHOLDER = '(none)'
export const FAL_HTTP_METHOD_POST = 'POST'
export const FAL_API_ERROR_LOG_PREFIX = '[FalClient] API Error:'
export const FAL_RAW_OUTPUT_LOG_PREFIX = '[FalClient] Raw output:'
