import {
  MARKET_SCORE_EMOJI_CRITICAL,
  MARKET_SCORE_EMOJI_HIGH,
  MARKET_SCORE_EMOJI_LOW,
  MARKET_SCORE_EMOJI_MEDIUM,
  MARKET_SCORE_THRESHOLD_HIGH,
  MARKET_SCORE_THRESHOLD_LOW,
  MARKET_SCORE_THRESHOLD_MEDIUM,
  MARKET_SCORE_TONE_CRITICAL,
  MARKET_SCORE_TONE_HIGH,
  MARKET_SCORE_TONE_LOW,
  MARKET_SCORE_TONE_MEDIUM,
} from '../constants/market-analysis-score'

export function getMarketScoreToneClass(score: number): string {
  if (score >= MARKET_SCORE_THRESHOLD_HIGH) return MARKET_SCORE_TONE_HIGH
  if (score >= MARKET_SCORE_THRESHOLD_MEDIUM) return MARKET_SCORE_TONE_MEDIUM
  if (score >= MARKET_SCORE_THRESHOLD_LOW) return MARKET_SCORE_TONE_LOW
  return MARKET_SCORE_TONE_CRITICAL
}

export function getMarketScoreEmoji(score: number): string {
  if (score >= MARKET_SCORE_THRESHOLD_HIGH) return MARKET_SCORE_EMOJI_HIGH
  if (score >= MARKET_SCORE_THRESHOLD_MEDIUM) return MARKET_SCORE_EMOJI_MEDIUM
  if (score >= MARKET_SCORE_THRESHOLD_LOW) return MARKET_SCORE_EMOJI_LOW
  return MARKET_SCORE_EMOJI_CRITICAL
}
