/**
 * Storyteller Relationships API
 *
 * Builds a relationship graph from ALL available data sources:
 * 0. LLM extraction (generateObject) — primary, grounded in story text with evidence
 * 1. entity_references table (with Voyage embeddings for similarity) — supplemental
 * 2. storyPlan factions (explicit membership/rivalry) — high confidence
 * 3. Text co-occurrence in worldDescription, plotTwists, faction descriptions
 *
 * Edge weights:
 * - LLM-extracted (0.6-1.0, with textual evidence)
 * - Explicit membership/rivalry (0.8-0.9)
 * - Embedding cosine similarity (supplemental, 0.45-1.0, labelled 'associated' only)
 * - Text co-occurrence (0.4-0.6)
 */

import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/db/client'
import { characters, entityReferences, projects, relationshipEdges } from '@/db'
import { eq, sql, and, gt } from 'drizzle-orm'
import { withAuth, type AuthenticatedRequest } from '@/shared/data/api-utils'
import {
  firstNonEmptyRecord,
  namedRecordsFromJson,
  readRowNumber,
  readRowString,
  readString,
  recordArrayFromJson,
  recordFromJson,
  sqlResultRows,
  stringArrayFromJson,
} from '@/shared/data/json-guards'
import { entityMetadata } from '@/domains/storyteller/core/entities/entity-type-guards'
import { StoryEntityType } from '@/domains/storyteller/core/entities/constants/entity-types'
import { StorytellerRelationshipType } from '@/domains/storyteller/services/constants/relationship-enricher'
import {
  EmbeddingSimilaritySqlColumn,
  GraphNodeIdPrefix,
  GraphNodeSource,
  GRAPH_NODE_TYPES,
  RelationshipsApiError,
  RelationshipsApiLog,
  RelationshipsQueryParam,
  RelationshipsQueryValue,
  RelationshipEdgeLabel,
  RELATIONSHIP_EDGE_DEFAULT_TYPE,
  RELATIONSHIPS_CENTRAL_CHARACTER_NONE,
} from '@/domains/storyteller/io/constants/relationships-api'

// =============================================================================
// TYPES
// =============================================================================

interface GraphNode {
  id: string
  name: string
  type: StoryEntityType
  metadata: Record<string, unknown>
}

interface GraphEdge {
  source: string
  target: string
  weight: number
  type: string
  label?: string
  /** Textual evidence from story content (LLM-extracted edges only) */
  evidence?: string
  /** Whether this edge was generated by the LLM extractor */
  llmGrounded?: boolean
}

interface RelationshipResponse {
  nodes: GraphNode[]
  edges: GraphEdge[]
  centralCharacter?: string
}

// =============================================================================
// HELPERS
// =============================================================================

function slugify(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '-')
}

function parseGraphNodeType(value: unknown): GraphNode['type'] | undefined {
  if (typeof value !== 'string') return undefined
  for (const nodeType of GRAPH_NODE_TYPES) {
    if (value === nodeType) return nodeType
  }
  return undefined
}

function addNode(
  nodes: GraphNode[],
  nodeIds: Set<string>,
  id: string,
  name: string,
  type: GraphNode['type'],
  metadata: Record<string, unknown> = {}
) {
  if (nodeIds.has(id)) return
  nodeIds.add(id)
  nodes.push({ id, name, type, metadata })
}

function addEdge(
  edges: GraphEdge[],
  edgeIds: Set<string>,
  source: string,
  target: string,
  weight: number,
  type: string,
  label?: string
) {
  const key = [source, target].sort().join('|')
  if (edgeIds.has(key)) return
  edgeIds.add(key)
  edges.push({ source, target, weight, type, label })
}

// =============================================================================
// MAIN
// =============================================================================

export const GET = withAuth(async (request: NextRequest, _auth: AuthenticatedRequest) => {
  try {
    const { searchParams } = new URL(request.url)
    const projectId = searchParams.get(RelationshipsQueryParam.ProjectId)

    if (!projectId) {
      return NextResponse.json({ error: RelationshipsApiError.MissingProjectId }, { status: 400 })
    }

    // ─── 1. Gather ALL data sources in parallel ─────────────────────────
    const [project, dbCharacters, dbEntities] = await Promise.all([
      db.query.projects.findFirst({
        where: eq(projects.id, projectId),
        with: { storyPlanTable: true },
      }),
      db.select().from(characters).where(eq(characters.projectId, projectId)),
      db
        .select({
          id: entityReferences.id,
          name: entityReferences.name,
          type: entityReferences.type,
          description: entityReferences.description,
          metadata: entityReferences.metadata,
          hasEmbedding: sql<boolean>`${entityReferences.embedding} IS NOT NULL`,
        })
        .from(entityReferences)
        .where(eq(entityReferences.projectId, projectId)),
    ])

    if (!project) {
      return NextResponse.json({ error: RelationshipsApiError.ProjectNotFound }, { status: 404 })
    }

    const storyPlan = firstNonEmptyRecord(project.storyPlanTable?.content, project.storyPlan)
    const seriesBible = recordFromJson(project.seriesBible)
    const factions = recordArrayFromJson(storyPlan.factions)
    const keyCharacters = namedRecordsFromJson(
      storyPlan.keyCharacters ?? storyPlan.cast ?? seriesBible.keyCharacters
    )
    const projectRecord = recordFromJson(project)
    const projectCast = namedRecordsFromJson(projectRecord.cast)

    // ─── 2. Build nodes from every source (deduplicated) ────────────────
    const nodes: GraphNode[] = []
    const nodeIds = new Set<string>()

    // Source A: entity_references table (highest priority - has embeddings)
    // Deduplicate by name+type (keep the one with embedding, or first occurrence)
    const seenEntityNames = new Map<string, string>() // "type:name" -> id
    for (const entity of dbEntities) {
      const key = `${entity.type}:${entity.name.toLowerCase()}`
      const duplicateId = seenEntityNames.get(key)
      if (duplicateId !== undefined) {
        // Skip duplicate - prefer one with embedding
        if (entity.hasEmbedding && !nodeIds.has(duplicateId)) {
          // This one has embedding, swap
          nodeIds.delete(duplicateId)
          const idx = nodes.findIndex(n => n.id === duplicateId)
          if (idx >= 0) nodes.splice(idx, 1)
        } else {
          continue // Skip duplicate
        }
      }
      seenEntityNames.set(key, entity.id)
      const nodeType = parseGraphNodeType(entity.type) ?? StoryEntityType.Character
      addNode(nodes, nodeIds, entity.id, entity.name, nodeType, {
        ...entityMetadata(entity.metadata),
        description: entity.description,
        hasEmbedding: entity.hasEmbedding,
        source: GraphNodeSource.EntityRegistry,
      })
    }

    // Source B: characters table
    for (const char of dbCharacters) {
      const id = `${GraphNodeIdPrefix.Character}${slugify(char.name)}`
      const charRecord = recordFromJson(char)
      addNode(nodes, nodeIds, id, char.name, StoryEntityType.Character, {
        role: char.role,
        archetype: readString(charRecord.archetype),
        motivation: readString(charRecord.motivation),
        source: GraphNodeSource.CharactersTable,
      })
    }

    // Source C: storyPlan.keyCharacters / cast
    for (const char of [...projectCast, ...keyCharacters]) {
      const id = `${GraphNodeIdPrefix.Character}${slugify(char.name)}`
      addNode(nodes, nodeIds, id, char.name, StoryEntityType.Character, {
        role: readString(char.role) ?? readString(char.archetype),
        archetype: readString(char.archetype),
        motivation: readString(char.motivation) ?? readString(char.description),
        source: GraphNodeSource.StoryPlan,
      })
    }

    // Source D: factions
    for (const faction of factions) {
      const name = readString(faction.name)
      if (!name) continue
      const id = `${GraphNodeIdPrefix.Faction}${slugify(name)}`
      addNode(nodes, nodeIds, id, name, StoryEntityType.Faction, {
        ideology: readString(faction.ideology),
        description: readString(faction.description),
        powerStructure: readString(faction.powerStructure),
        source: GraphNodeSource.StoryPlan,
      })
    }

    // ─── 2b. Build canonical name→ID map (Phase 2: entity resolution) ───
    // The same character can appear as:
    //   - entity-registry UUID       (from entity_references)
    //   - "character-${slug}"        (from characters table or storyPlan cast)
    // We prefer the entity-registry UUID (has embeddings) and remap all slug IDs.
    const canonicalMap = new Map<string, string>() // slug-ID → canonical UUID
    for (const node of nodes) {
      // Build reverse: for each UUID node, find if there's a slug version
      if (!node.id.startsWith(GraphNodeIdPrefix.Character) && !node.id.startsWith(GraphNodeIdPrefix.Faction)) {
        // This is a UUID from entity_references
        const slugId = `${node.type}-${slugify(node.name)}`
        if (nodeIds.has(slugId) && slugId !== node.id) {
          // Merge slug node into UUID node
          canonicalMap.set(slugId, node.id)
          // Remove the slug duplicate node
          const idx = nodes.findIndex(n => n.id === slugId)
          if (idx >= 0) nodes.splice(idx, 1)
          nodeIds.delete(slugId)
          console.log(`[Relationships] Merged duplicate node: ${slugId} → ${node.id}`)
        }
      }
    }
    // Remap nodeIds after merge
    const canonicalNodeId = (id: string) => canonicalMap.get(id) ?? id

    // ─── 3. Build edges using multiple strategies ───────────────────────
    const edges: GraphEdge[] = []
    const edgeIds = new Set<string>()

    // ─── Cache Strategy -1: Read pre-computed edges from DB ─────────────
    // If we have fresh edges in relationship_edges (< 30 min old), return
    // them directly without running LLM extraction. This makes page loads O(1).
    const EDGE_CACHE_TTL_MS = 30 * 60 * 1000 // 30 minutes
    const cacheThreshold = new Date(Date.now() - EDGE_CACHE_TTL_MS)
    const refreshParam = new URL(request.url).searchParams.get(RelationshipsQueryParam.Refresh)
    const forceRefresh = refreshParam === RelationshipsQueryValue.RefreshTrue

    if (!forceRefresh) {
      try {
        const cachedEdges = await db
          .select()
          .from(relationshipEdges)
          .where(
            and(
              eq(relationshipEdges.projectId, projectId),
              gt(relationshipEdges.extractedAt, cacheThreshold)
            )
          )

        if (cachedEdges.length > 0) {
          // Return cached graph — fast path
          const cachedEdgeList: GraphEdge[] = cachedEdges.map(e => ({
            source: canonicalNodeId(e.sourceId),
            target: canonicalNodeId(e.targetId),
            weight: e.weight,
            type: e.relationshipType,
            label: e.label ?? e.relationshipType.replace(/_/g, ' '),
            evidence: e.evidence ?? undefined,
            llmGrounded: e.llmGrounded,
          }))

          const validCachedEdges = cachedEdgeList.filter(
            e => nodeIds.has(e.source) && nodeIds.has(e.target)
          )

          if (validCachedEdges.length > 0) {
            console.log(`[Relationships] DB cache hit: ${validCachedEdges.length} edges (skipping LLM)`)

            const centrality = new Map<string, number>()
            for (const node of nodes) centrality.set(node.id, 0)
            for (const edge of validCachedEdges) {
              centrality.set(edge.source, (centrality.get(edge.source) || 0) + edge.weight)
              centrality.set(edge.target, (centrality.get(edge.target) || 0) + edge.weight)
            }
            let centralCharacter: string | undefined
            let maxCentrality = 0
            for (const [id, score] of centrality) {
              if (score > maxCentrality) { maxCentrality = score; centralCharacter = id }
            }

            return NextResponse.json({ nodes, edges: validCachedEdges, centralCharacter } satisfies RelationshipResponse)
          }
        }
      } catch (err) {
        console.warn(RelationshipsApiLog.DbCacheReadFailed, err)
      }
    }

    // ─── Strategy 0: LLM-Grounded Extraction (highest priority) ─────────
    // TEMPORARILY DISABLED: relationship-extractor service is missing from the codebase.
    // Falling back to Strategy 1-3 heuristics.

    // ─── Strategy 1: Embedding similarity (pgvector cosine distance) ────
    // Supplemental only — used for entities not covered by LLM extraction.
    // IMPORTANT: We do NOT fabricate ally/rival labels from threshold alone.
    // Embedding similarity tells us entities are semantically related,
    // NOT the narrative type of that relationship.
    const entitiesWithEmbeddings = dbEntities.filter(e => e.hasEmbedding)

    if (entitiesWithEmbeddings.length >= 2) {
      try {
        const pairwiseResult = await db.execute(sql`
          SELECT 
            a.id as source_id,
            b.id as target_id,
            a.name as source_name,
            b.name as target_name,
            a.type as source_type,
            b.type as target_type,
            1 - (a.embedding <=> b.embedding) as similarity
          FROM entity_references a
          CROSS JOIN entity_references b
          WHERE a.project_id = ${projectId}
            AND b.project_id = ${projectId}
            AND a.id < b.id
            AND a.embedding IS NOT NULL
            AND b.embedding IS NOT NULL
            AND 1 - (a.embedding <=> b.embedding) > 0.55
          ORDER BY similarity DESC
          LIMIT 50
        `)

        for (const row of sqlResultRows(pairwiseResult)) {
          const sourceType = readRowString(row, EmbeddingSimilaritySqlColumn.SourceType) ?? ''
          const targetType = readRowString(row, EmbeddingSimilaritySqlColumn.TargetType) ?? ''
          const similarity = readRowNumber(row, EmbeddingSimilaritySqlColumn.Similarity) ?? 0
          const sourceId = readRowString(row, EmbeddingSimilaritySqlColumn.SourceId)
          const targetId = readRowString(row, EmbeddingSimilaritySqlColumn.TargetId)
          if (!sourceId || !targetId) continue

          // Only add if not already covered by an LLM-grounded edge
          const key = [sourceId, targetId].sort().join('|')
          if (edgeIds.has(key)) continue

          // Structural cross-type relationships are safe to infer directly.
          // Same-type (character-character, faction-faction) get a generic
          // 'associated' label — never fabricate ally/rival from thresholds.
          let relType = RELATIONSHIP_EDGE_DEFAULT_TYPE
          let label = RelationshipEdgeLabel.Connected

          if (
            (sourceType === StoryEntityType.Character && targetType === StoryEntityType.Faction) ||
            (sourceType === StoryEntityType.Faction && targetType === StoryEntityType.Character)
          ) {
            relType = RELATIONSHIP_EDGE_DEFAULT_TYPE
            label = RelationshipEdgeLabel.Affiliated
          } else if (sourceType === StoryEntityType.Place || targetType === StoryEntityType.Place) {
            relType = RELATIONSHIP_EDGE_DEFAULT_TYPE
            label = RelationshipEdgeLabel.LocatedIn
          }

          addEdge(edges, edgeIds, sourceId, targetId, similarity, relType, label)
        }

        console.log(`[Relationships] Embedding similarity: added supplemental edges, total now ${edges.length}`)
      } catch (err) {
        console.warn(RelationshipsApiLog.EmbeddingSimilarityFailed, err)
      }
    }

    // Strategy 2: Explicit faction membership and rivalries
    for (const faction of factions) {
      const factionName = readString(faction.name)
      if (!factionName) continue
      const factionId = `${GraphNodeIdPrefix.Faction}${slugify(factionName)}`

      const members = [
        ...stringArrayFromJson(faction.members),
        ...stringArrayFromJson(faction.keyMembers),
      ]
      for (const member of members) {
        const charId = `${GraphNodeIdPrefix.Character}${slugify(member)}`
        if (nodeIds.has(charId)) {
          addEdge(edges, edgeIds, charId, factionId, 0.9, StorytellerRelationshipType.MemberOf, RelationshipEdgeLabel.Member)
        }
      }

      for (const rival of stringArrayFromJson(faction.rivals)) {
        const rivalId = `${GraphNodeIdPrefix.Faction}${slugify(rival)}`
        if (nodeIds.has(rivalId)) {
          addEdge(edges, edgeIds, factionId, rivalId, 0.8, StorytellerRelationshipType.Rival, RelationshipEdgeLabel.Rivals)
        }
      }
    }

    const plotTwistText = recordArrayFromJson(storyPlan.plotTwists).map(pt => {
      return [
        readString(pt.title),
        readString(pt.description),
        readString(pt.impact),
        readString(pt.foreshadowing),
      ]
        .filter(Boolean)
        .join(' ')
    })

    const factionText = factions.map(f => {
      return [
        readString(f.name),
        readString(f.description),
        readString(f.powerStructure),
        readString(f.politicalForces),
      ]
        .filter(Boolean)
        .join(' ')
    })

    // Strategy 3: Text co-occurrence (world description, plot twists, faction descriptions)
    const allText = [
      readString(storyPlan.worldDescription) ?? '',
      ...plotTwistText,
      ...factionText,
    ]
      .join('\n')
      .toLowerCase()

    if (allText.length > 50) {
      // Split into paragraphs for locality
      const paragraphs = allText.split(/\n\n|\.\s+/).filter(p => p.length > 20)

      for (const paragraph of paragraphs) {
        const mentionedNodes = nodes.filter(n => paragraph.includes(n.name.toLowerCase()))

        // Entities mentioned in same paragraph are related
        for (let i = 0; i < mentionedNodes.length; i++) {
          for (let j = i + 1; j < mentionedNodes.length; j++) {
            const a = mentionedNodes[i]
            const b = mentionedNodes[j]

            let relType = RELATIONSHIP_EDGE_DEFAULT_TYPE
            if (
              (a.type === StoryEntityType.Character && b.type === StoryEntityType.Faction) ||
              (a.type === StoryEntityType.Faction && b.type === StoryEntityType.Character)
            ) {
              relType = StorytellerRelationshipType.MemberOf
            }

            addEdge(edges, edgeIds, a.id, b.id, 0.5, relType, RelationshipEdgeLabel.CoMentioned)
          }
        }
      }
    }

    // NOTE: Full-mesh fallback removed.
    // Showing no edges is more honest than fabricating 0.25-weight phantom connections.
    // The LLM extractor (Strategy 0) will find real relationships if the story has them.
    if (edges.length === 0) {
      console.log(RelationshipsApiLog.NoEdgesFound)
    }

    // Filter edges to only reference existing nodes
    const validEdges = edges.filter(e => nodeIds.has(e.source) && nodeIds.has(e.target))

    // ─── 4. Compute centrality ──────────────────────────────────────────
    const centrality = new Map<string, number>()
    for (const node of nodes) centrality.set(node.id, 0)
    for (const edge of validEdges) {
      centrality.set(edge.source, (centrality.get(edge.source) || 0) + edge.weight)
      centrality.set(edge.target, (centrality.get(edge.target) || 0) + edge.weight)
    }

    let centralCharacter: string | undefined
    let maxCentrality = 0
    for (const [id, score] of centrality) {
      if (score > maxCentrality) {
        maxCentrality = score
        centralCharacter = id
      }
    }

    console.log(
      `[Relationships] Final: ${nodes.length} nodes, ${validEdges.length} edges (${edges.length - validEdges.length} orphaned removed), central: ${centralCharacter || RELATIONSHIPS_CENTRAL_CHARACTER_NONE}`
    )

    return NextResponse.json({
      nodes,
      edges: validEdges,
      centralCharacter,
    } satisfies RelationshipResponse)
  } catch (error) {
    console.error(RelationshipsApiLog.ApiFailed, error)
    return NextResponse.json({ error: RelationshipsApiError.FetchFailed }, { status: 500 })
  }
})
