/**
 * Storyteller Relationships API
 *
 * Builds a relationship graph from ALL available data sources:
 * 0. LLM extraction (generateObject) — primary, grounded in story text with evidence
 * 1. entity_references table (with Voyage embeddings for similarity) — supplemental
 * 2. storyPlan factions (explicit membership/rivalry) — high confidence
 * 3. Text co-occurrence in worldDescription, plotTwists, faction descriptions
 *
 * Edge weights:
 * - LLM-extracted (0.6-1.0, with textual evidence)
 * - Explicit membership/rivalry (0.8-0.9)
 * - Embedding cosine similarity (supplemental, 0.45-1.0, labelled 'associated' only)
 * - Text co-occurrence (0.4-0.6)
 */

import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { projects, characters, entityReferences, relationshipEdges } from '@/domains/storyteller/db/schema'
import { eq, sql, and, gt } from 'drizzle-orm'
import { withAuth, type AuthenticatedRequest } from '@/lib/api-utils'

// =============================================================================
// TYPES
// =============================================================================

interface GraphNode {
  id: string
  name: string
  type: 'character' | 'faction' | 'place' | 'event' | 'rule'
  metadata: Record<string, unknown>
}

interface GraphEdge {
  source: string
  target: string
  weight: number
  type: string
  label?: string
  /** Textual evidence from story content (LLM-extracted edges only) */
  evidence?: string
  /** Whether this edge was generated by the LLM extractor */
  llmGrounded?: boolean
}

interface RelationshipResponse {
  nodes: GraphNode[]
  edges: GraphEdge[]
  centralCharacter?: string
}

// =============================================================================
// HELPERS
// =============================================================================

function slugify(name: string): string {
  return name.toLowerCase().replace(/\s+/g, '-')
}

function addNode(
  nodes: GraphNode[],
  nodeIds: Set<string>,
  id: string,
  name: string,
  type: GraphNode['type'],
  metadata: Record<string, unknown> = {}
) {
  if (nodeIds.has(id)) return
  nodeIds.add(id)
  nodes.push({ id, name, type, metadata })
}

function addEdge(
  edges: GraphEdge[],
  edgeIds: Set<string>,
  source: string,
  target: string,
  weight: number,
  type: string,
  label?: string
) {
  const key = [source, target].sort().join('|')
  if (edgeIds.has(key)) return
  edgeIds.add(key)
  edges.push({ source, target, weight, type, label })
}

// =============================================================================
// MAIN
// =============================================================================

export const GET = withAuth<any>(async (request: NextRequest, _auth: AuthenticatedRequest) => {
  try {
    const { searchParams } = new URL(request.url)
    const projectId = searchParams.get('projectId')

    if (!projectId) {
      return NextResponse.json({ error: 'Missing projectId' }, { status: 400 })
    }

    // ─── 1. Gather ALL data sources in parallel ─────────────────────────
    const [project, dbCharacters, dbEntities] = await Promise.all([
      db.query.projects.findFirst({
        where: eq(projects.id, projectId),
        with: { storyPlanTable: true },
      }),
      db.select().from(characters).where(eq(characters.projectId, projectId)),
      db
        .select({
          id: entityReferences.id,
          name: entityReferences.name,
          type: entityReferences.type,
          description: entityReferences.description,
          metadata: entityReferences.metadata,
          hasEmbedding: sql<boolean>`${entityReferences.embedding} IS NOT NULL`,
        })
        .from(entityReferences)
        .where(eq(entityReferences.projectId, projectId)),
    ])

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    const storyPlan = (project.storyPlanTable?.content as any) || (project.storyPlan as any) || {}
    const seriesBible = (project.seriesBible as any) || {}
    const factions = (storyPlan.factions || []) as any[]
    const keyCharacters = (storyPlan.keyCharacters ||
      storyPlan.cast ||
      seriesBible.keyCharacters ||
      []) as any[]
    const projectCast = ((project as any).cast || []) as any[]
    const projectTitle = (project as any).name || storyPlan.title || 'Untitled'

    // ─── 2. Build nodes from every source (deduplicated) ────────────────
    const nodes: GraphNode[] = []
    const nodeIds = new Set<string>()

    // Source A: entity_references table (highest priority - has embeddings)
    // Deduplicate by name+type (keep the one with embedding, or first occurrence)
    const seenEntityNames = new Map<string, string>() // "type:name" -> id
    for (const entity of dbEntities) {
      const key = `${entity.type}:${entity.name.toLowerCase()}`
      if (seenEntityNames.has(key)) {
        // Skip duplicate - prefer one with embedding
        if (entity.hasEmbedding && !nodeIds.has(seenEntityNames.get(key)!)) {
          // This one has embedding, swap
          const oldId = seenEntityNames.get(key)!
          nodeIds.delete(oldId)
          const idx = nodes.findIndex(n => n.id === oldId)
          if (idx >= 0) nodes.splice(idx, 1)
        } else {
          continue // Skip duplicate
        }
      }
      seenEntityNames.set(key, entity.id)
      addNode(nodes, nodeIds, entity.id, entity.name, entity.type as GraphNode['type'], {
        ...((entity.metadata as any) || {}),
        description: entity.description,
        hasEmbedding: entity.hasEmbedding,
        source: 'entity_registry',
      })
    }

    // Source B: characters table
    for (const char of dbCharacters) {
      const charAny = char as any
      const id = `character-${slugify(char.name)}`
      addNode(nodes, nodeIds, id, char.name, 'character', {
        role: char.role,
        archetype: charAny.archetype,
        motivation: charAny.motivation,
        source: 'characters_table',
      })
    }

    // Source C: storyPlan.keyCharacters / cast
    for (const char of [...projectCast, ...keyCharacters]) {
      if (!char?.name) continue
      const id = `character-${slugify(char.name)}`
      addNode(nodes, nodeIds, id, char.name, 'character', {
        role: char.role || char.archetype,
        archetype: char.archetype,
        motivation: char.motivation || char.description,
        source: 'story_plan',
      })
    }

    // Source D: factions
    for (const faction of factions) {
      if (!faction?.name) continue
      const id = `faction-${slugify(faction.name)}`
      addNode(nodes, nodeIds, id, faction.name, 'faction', {
        ideology: faction.ideology,
        description: faction.description,
        powerStructure: faction.powerStructure,
        source: 'story_plan',
      })
    }

    // ─── 2b. Build canonical name→ID map (Phase 2: entity resolution) ───
    // The same character can appear as:
    //   - entity-registry UUID       (from entity_references)
    //   - "character-${slug}"        (from characters table or storyPlan cast)
    // We prefer the entity-registry UUID (has embeddings) and remap all slug IDs.
    const canonicalMap = new Map<string, string>() // slug-ID → canonical UUID
    for (const node of nodes) {
      // Build reverse: for each UUID node, find if there's a slug version
      if (!node.id.startsWith('character-') && !node.id.startsWith('faction-')) {
        // This is a UUID from entity_references
        const slugId = `${node.type}-${slugify(node.name)}`
        if (nodeIds.has(slugId) && slugId !== node.id) {
          // Merge slug node into UUID node
          canonicalMap.set(slugId, node.id)
          // Remove the slug duplicate node
          const idx = nodes.findIndex(n => n.id === slugId)
          if (idx >= 0) nodes.splice(idx, 1)
          nodeIds.delete(slugId)
          console.log(`[Relationships] Merged duplicate node: ${slugId} → ${node.id}`)
        }
      }
    }
    // Remap nodeIds after merge
    const canonicalNodeId = (id: string) => canonicalMap.get(id) ?? id

    // ─── 3. Build edges using multiple strategies ───────────────────────
    const edges: GraphEdge[] = []
    const edgeIds = new Set<string>()

    // ─── Cache Strategy -1: Read pre-computed edges from DB ─────────────
    // If we have fresh edges in relationship_edges (< 30 min old), return
    // them directly without running LLM extraction. This makes page loads O(1).
    const EDGE_CACHE_TTL_MS = 30 * 60 * 1000 // 30 minutes
    const cacheThreshold = new Date(Date.now() - EDGE_CACHE_TTL_MS)
    const refreshParam = new URL(request.url).searchParams.get('refresh')
    const forceRefresh = refreshParam === 'true'

    if (!forceRefresh) {
      try {
        const cachedEdges = await db
          .select()
          .from(relationshipEdges)
          .where(
            and(
              eq(relationshipEdges.projectId, projectId),
              gt(relationshipEdges.extractedAt, cacheThreshold)
            )
          )

        if (cachedEdges.length > 0) {
          // Return cached graph — fast path
          const cachedEdgeList: GraphEdge[] = cachedEdges.map(e => ({
            source: canonicalNodeId(e.sourceId),
            target: canonicalNodeId(e.targetId),
            weight: e.weight,
            type: e.relationshipType,
            label: e.label ?? e.relationshipType.replace(/_/g, ' '),
            evidence: e.evidence ?? undefined,
            llmGrounded: e.llmGrounded,
          }))

          const validCachedEdges = cachedEdgeList.filter(
            e => nodeIds.has(e.source) && nodeIds.has(e.target)
          )

          if (validCachedEdges.length > 0) {
            console.log(`[Relationships] DB cache hit: ${validCachedEdges.length} edges (skipping LLM)`)

            const centrality = new Map<string, number>()
            for (const node of nodes) centrality.set(node.id, 0)
            for (const edge of validCachedEdges) {
              centrality.set(edge.source, (centrality.get(edge.source) || 0) + edge.weight)
              centrality.set(edge.target, (centrality.get(edge.target) || 0) + edge.weight)
            }
            let centralCharacter: string | undefined
            let maxCentrality = 0
            for (const [id, score] of centrality) {
              if (score > maxCentrality) { maxCentrality = score; centralCharacter = id }
            }

            return NextResponse.json({ nodes, edges: validCachedEdges, centralCharacter } satisfies RelationshipResponse)
          }
        }
      } catch (err) {
        console.warn('[Relationships] DB cache read failed, continuing with live extraction:', err)
      }
    }

    // ─── Strategy 0: LLM-Grounded Extraction (highest priority) ─────────
    // TEMPORARILY DISABLED: relationship-extractor service is missing from the codebase.
    // Falling back to Strategy 1-3 heuristics.

    // ─── Strategy 1: Embedding similarity (pgvector cosine distance) ────
    // Supplemental only — used for entities not covered by LLM extraction.
    // IMPORTANT: We do NOT fabricate ally/rival labels from threshold alone.
    // Embedding similarity tells us entities are semantically related,
    // NOT the narrative type of that relationship.
    const entitiesWithEmbeddings = dbEntities.filter(e => e.hasEmbedding)

    if (entitiesWithEmbeddings.length >= 2) {
      try {
        const pairwiseResult = await db.execute(sql`
          SELECT 
            a.id as source_id,
            b.id as target_id,
            a.name as source_name,
            b.name as target_name,
            a.type as source_type,
            b.type as target_type,
            1 - (a.embedding <=> b.embedding) as similarity
          FROM entity_references a
          CROSS JOIN entity_references b
          WHERE a.project_id = ${projectId}
            AND b.project_id = ${projectId}
            AND a.id < b.id
            AND a.embedding IS NOT NULL
            AND b.embedding IS NOT NULL
            AND 1 - (a.embedding <=> b.embedding) > 0.55
          ORDER BY similarity DESC
          LIMIT 50
        `)

        for (const row of (pairwiseResult.rows || pairwiseResult) as any[]) {
          const sourceType = row.source_type as string
          const targetType = row.target_type as string
          const similarity = parseFloat(row.similarity)

          // Only add if not already covered by an LLM-grounded edge
          const key = [row.source_id, row.target_id].sort().join('|')
          if (edgeIds.has(key)) continue

          // Structural cross-type relationships are safe to infer directly.
          // Same-type (character-character, faction-faction) get a generic
          // 'associated' label — never fabricate ally/rival from thresholds.
          let relType = 'associated'
          let label = 'Connected'

          if (
            (sourceType === 'character' && targetType === 'faction') ||
            (sourceType === 'faction' && targetType === 'character')
          ) {
            relType = 'associated'
            label = 'Affiliated'
          } else if (sourceType === 'place' || targetType === 'place') {
            relType = 'associated'
            label = 'Located in'
          }

          addEdge(edges, edgeIds, row.source_id, row.target_id, similarity, relType, label)
        }

        console.log(`[Relationships] Embedding similarity: added supplemental edges, total now ${edges.length}`)
      } catch (err) {
        console.warn('[Relationships] Embedding similarity query failed:', err)
      }
    }

    // Strategy 2: Explicit faction membership and rivalries
    for (const faction of factions) {
      if (!faction?.name) continue
      const factionId = `faction-${slugify(faction.name)}`

      // Members
      const members = [...(faction.members || []), ...(faction.keyMembers || [])]
      for (const member of members) {
        const charId = `character-${slugify(member)}`
        if (nodeIds.has(charId)) {
          addEdge(edges, edgeIds, charId, factionId, 0.9, 'member_of', 'Member')
        }
      }

      // Rivals
      for (const rival of faction.rivals || []) {
        const rivalId = `faction-${slugify(rival)}`
        if (nodeIds.has(rivalId)) {
          addEdge(edges, edgeIds, factionId, rivalId, 0.8, 'rival', 'Rivals')
        }
      }
    }

    // Strategy 3: Text co-occurrence (world description, plot twists, faction descriptions)
    const allText = [
      storyPlan.worldDescription || '',
      ...(storyPlan.plotTwists || []).map(
        (pt: any) =>
          `${pt.title || ''} ${pt.description || ''} ${pt.impact || ''} ${pt.foreshadowing || ''}`
      ),
      ...factions.map(
        (f: any) =>
          `${f.name || ''} ${f.description || ''} ${f.powerStructure || ''} ${f.politicalForces || ''}`
      ),
    ]
      .join('\n')
      .toLowerCase()

    if (allText.length > 50) {
      // Split into paragraphs for locality
      const paragraphs = allText.split(/\n\n|\.\s+/).filter(p => p.length > 20)

      for (const paragraph of paragraphs) {
        const mentionedNodes = nodes.filter(n => paragraph.includes(n.name.toLowerCase()))

        // Entities mentioned in same paragraph are related
        for (let i = 0; i < mentionedNodes.length; i++) {
          for (let j = i + 1; j < mentionedNodes.length; j++) {
            const a = mentionedNodes[i]
            const b = mentionedNodes[j]

            let relType = 'associated'
            if (
              (a.type === 'character' && b.type === 'faction') ||
              (a.type === 'faction' && b.type === 'character')
            ) {
              relType = 'member_of'
            }

            addEdge(edges, edgeIds, a.id, b.id, 0.5, relType, 'Co-mentioned')
          }
        }
      }
    }

    // NOTE: Full-mesh fallback removed.
    // Showing no edges is more honest than fabricating 0.25-weight phantom connections.
    // The LLM extractor (Strategy 0) will find real relationships if the story has them.
    if (edges.length === 0) {
      console.log('[Relationships] No edges found — story may not have documented relationships yet')
    }

    // Filter edges to only reference existing nodes
    const validEdges = edges.filter(e => nodeIds.has(e.source) && nodeIds.has(e.target))

    // ─── 4. Compute centrality ──────────────────────────────────────────
    const centrality = new Map<string, number>()
    for (const node of nodes) centrality.set(node.id, 0)
    for (const edge of validEdges) {
      centrality.set(edge.source, (centrality.get(edge.source) || 0) + edge.weight)
      centrality.set(edge.target, (centrality.get(edge.target) || 0) + edge.weight)
    }

    let centralCharacter: string | undefined
    let maxCentrality = 0
    for (const [id, score] of centrality) {
      if (score > maxCentrality) {
        maxCentrality = score
        centralCharacter = id
      }
    }

    console.log(
      `[Relationships] Final: ${nodes.length} nodes, ${validEdges.length} edges (${edges.length - validEdges.length} orphaned removed), central: ${centralCharacter || 'none'}`
    )

    return NextResponse.json({
      nodes,
      edges: validEdges,
      centralCharacter,
    } satisfies RelationshipResponse)
  } catch (error) {
    console.error('[Relationships API] Failed:', error)
    return NextResponse.json({ error: 'Failed to fetch relationships' }, { status: 500 })
  }
})
