/**
 * Types for CharacterWeb component
 */

import { Node, Edge } from '@xyflow/react'
import { StoryEntityType } from '@/domains/storyteller/core/entities/constants/entity-types'
import {
  recordFromJson,
  recordArrayFromJson,
  readString,
  readNumber,
} from '@/shared/data/json-guards'
import {
  parseRelationshipType,
  RELATIONSHIP_DEFAULT_TYPE,
  RELATIONSHIP_STYLES,
  type RelationshipType,
} from './constants/relationship-web-styles'

export type { RelationshipType }
export {
  parseRelationshipType,
  RELATIONSHIP_DEFAULT_TYPE,
  RELATIONSHIP_STYLES,
}

export function readRelationshipEdgeEvidence(
  data: RelationshipEdgeData | undefined
): string | undefined {
  const evidence = data?.evidence
  return typeof evidence === 'string' ? evidence : undefined
}

export function readRelationshipEdgeLlmGrounded(
  data: RelationshipEdgeData | undefined
): boolean | undefined {
  const grounded = data?.llmGrounded
  return typeof grounded === 'boolean' ? grounded : undefined
}

export interface CharacterNodeData {
  [k: string]: unknown
  name: string
  role?: string
  avatarUrl?: string
  description?: string
  type: `${StoryEntityType}`
  // Metrics for visualization
  stressLevel?: number // 0-100
  transformationProgress?: number // 0-100
  // For highlighting
  isHighlighted?: boolean
  isCentral?: boolean
  /** Entity is the focused/navigated-to entity (cyan ring) */
  isSelected?: boolean
}

export interface RelationshipEdgeData {
  [k: string]: unknown
  relationshipType: RelationshipType
  strength: number // 0-1
  trust?: number // -1 to 1
  dynamic?: string
  /** Textual evidence from LLM extraction (story text quote/paraphrase) */
  evidence?: string
  /** True when this edge was generated by the LLM extractor (most accurate) */
  llmGrounded?: boolean
  history?: Array<{
    beatId: string
    change: string
  }>
}

// Node type for React Flow
export type CharacterWebNode = Node<CharacterNodeData>

// Edge type for React Flow
export type CharacterWebEdge = Edge<RelationshipEdgeData>

// API response types
export interface RelationshipMatrixResponse {
  nodes: Array<{
    id: string
    name: string
    type: `${StoryEntityType}`
    description?: string
    metadata: {
      role?: string
      archetype?: string
      description?: string
      metrics?: {
        perceivedStakes?: number
        transformation?: number
      }
      [key: string]: unknown
    }
  }>
  edges: Array<{
    source: string
    target: string
    weight: number
    type: string
    label?: string
    /** Textual evidence from LLM extraction */
    evidence?: string
    /** True when grounded by LLM extraction, not purely cosine similarity */
    llmGrounded?: boolean
  }>
  centralCharacter?: string
}

type MatrixNode = RelationshipMatrixResponse['nodes'][number]
type MatrixNodeMetadata = MatrixNode['metadata']
type MatrixEdge = RelationshipMatrixResponse['edges'][number]

function nodeMetadataFromJson(value: unknown): MatrixNodeMetadata {
  const raw = recordFromJson(value)
  const metadata: MatrixNodeMetadata = {}
  // Preserve arbitrary extra keys (index signature is `unknown`).
  for (const [key, entry] of Object.entries(raw)) {
    metadata[key] = entry
  }
  const role = readString(raw.role)
  if (role !== undefined) metadata.role = role
  const archetype = readString(raw.archetype)
  if (archetype !== undefined) metadata.archetype = archetype
  const description = readString(raw.description)
  if (description !== undefined) metadata.description = description

  const rawMetrics = recordFromJson(raw.metrics)
  const metrics: NonNullable<MatrixNodeMetadata['metrics']> = {}
  const perceivedStakes = readNumber(rawMetrics.perceivedStakes)
  if (perceivedStakes !== undefined) metrics.perceivedStakes = perceivedStakes
  const transformation = readNumber(rawMetrics.transformation)
  if (transformation !== undefined) metrics.transformation = transformation
  metadata.metrics = metrics
  return metadata
}

function nodeTypeFromJson(value: unknown): `${StoryEntityType}` {
  const type = readString(value)
  return Object.values(StoryEntityType).find(t => t === type) ?? StoryEntityType.Character
}

/** Parse the untyped relationships API payload without `as` casts. */
export function relationshipMatrixFromJson(value: unknown): RelationshipMatrixResponse {
  const root = recordFromJson(value)
  const nodes: MatrixNode[] = recordArrayFromJson(root.nodes).map(raw => {
    const node: MatrixNode = {
      id: readString(raw.id) ?? '',
      name: readString(raw.name) ?? '',
      type: nodeTypeFromJson(raw.type),
      metadata: nodeMetadataFromJson(raw.metadata),
    }
    const description = readString(raw.description)
    if (description !== undefined) node.description = description
    return node
  })

  const edges: MatrixEdge[] = recordArrayFromJson(root.edges).map(raw => {
    const edge: MatrixEdge = {
      source: readString(raw.source) ?? '',
      target: readString(raw.target) ?? '',
      weight: readNumber(raw.weight) ?? 0,
      type: readString(raw.type) ?? '',
    }
    const label = readString(raw.label)
    if (label !== undefined) edge.label = label
    const evidence = readString(raw.evidence)
    if (evidence !== undefined) edge.evidence = evidence
    if (typeof raw.llmGrounded === 'boolean') edge.llmGrounded = raw.llmGrounded
    return edge
  })

  const result: RelationshipMatrixResponse = { nodes, edges }
  const centralCharacter = readString(root.centralCharacter)
  if (centralCharacter !== undefined) result.centralCharacter = centralCharacter
  return result
}
