/**
 * Types for CharacterWeb component
 */

import { Node, Edge } from '@xyflow/react'
import { StoryEntityType } from '@/domains/storyteller/core/entities/constants/entity-types'
import {
  parseRelationshipType,
  RELATIONSHIP_DEFAULT_TYPE,
  RELATIONSHIP_STYLES,
  type RelationshipType,
} from './constants/relationship-web-styles'

export type { RelationshipType }
export {
  parseRelationshipType,
  RELATIONSHIP_DEFAULT_TYPE,
  RELATIONSHIP_STYLES,
}

export function readRelationshipEdgeEvidence(
  data: RelationshipEdgeData | undefined
): string | undefined {
  const evidence = data?.evidence
  return typeof evidence === 'string' ? evidence : undefined
}

export function readRelationshipEdgeLlmGrounded(
  data: RelationshipEdgeData | undefined
): boolean | undefined {
  const grounded = data?.llmGrounded
  return typeof grounded === 'boolean' ? grounded : undefined
}

export interface CharacterNodeData {
  [k: string]: unknown
  name: string
  role?: string
  avatarUrl?: string
  description?: string
  type: `${StoryEntityType}`
  // Metrics for visualization
  stressLevel?: number // 0-100
  transformationProgress?: number // 0-100
  // For highlighting
  isHighlighted?: boolean
  isCentral?: boolean
  /** Entity is the focused/navigated-to entity (cyan ring) */
  isSelected?: boolean
}

export interface RelationshipEdgeData {
  [k: string]: unknown
  relationshipType: RelationshipType
  strength: number // 0-1
  trust?: number // -1 to 1
  dynamic?: string
  /** Textual evidence from LLM extraction (story text quote/paraphrase) */
  evidence?: string
  /** True when this edge was generated by the LLM extractor (most accurate) */
  llmGrounded?: boolean
  history?: Array<{
    beatId: string
    change: string
  }>
}

// Node type for React Flow
export type CharacterWebNode = Node<CharacterNodeData>

// Edge type for React Flow
export type CharacterWebEdge = Edge<RelationshipEdgeData>

// API response types
export interface RelationshipMatrixResponse {
  nodes: Array<{
    id: string
    name: string
    type: `${StoryEntityType}`
    description?: string
    metadata: {
      role?: string
      archetype?: string
      description?: string
      metrics?: {
        perceivedStakes?: number
        transformation?: number
      }
      [key: string]: unknown
    }
  }>
  edges: Array<{
    source: string
    target: string
    weight: number
    type: string
    label?: string
    /** Textual evidence from LLM extraction */
    evidence?: string
    /** True when grounded by LLM extraction, not purely cosine similarity */
    llmGrounded?: boolean
  }>
  centralCharacter?: string
}
