/**
 * Types for CharacterWeb component
 */

import { Node, Edge } from '@xyflow/react'

export type RelationshipType =
  | 'ally'
  | 'enemy'
  | 'rival'
  | 'mentor'
  | 'student'
  | 'lover'
  | 'family'
  | 'member_of'
  | 'leader_of'
  | 'associated'
  | 'related'
  | 'owns'
  | 'uses'
  | 'caused_by'
  | 'happened_at'
  | 'located_in'
  | 'temporal'
  | 'stranger'
  | 'acquaintance'
  | 'complex'

const RELATIONSHIP_TYPES: RelationshipType[] = [
  'ally',
  'enemy',
  'rival',
  'mentor',
  'student',
  'lover',
  'family',
  'member_of',
  'leader_of',
  'associated',
  'related',
  'owns',
  'uses',
  'caused_by',
  'happened_at',
  'located_in',
  'temporal',
  'stranger',
  'acquaintance',
  'complex',
]

const RELATIONSHIP_TYPE_SET = new Set<string>(RELATIONSHIP_TYPES)

export function parseRelationshipType(value: string | undefined): RelationshipType {
  if (value && RELATIONSHIP_TYPE_SET.has(value)) {
    for (const type of RELATIONSHIP_TYPES) {
      if (type === value) return type
    }
  }
  return 'related'
}

export function readRelationshipEdgeEvidence(
  data: RelationshipEdgeData | undefined
): string | undefined {
  const evidence = data?.evidence
  return typeof evidence === 'string' ? evidence : undefined
}

export function readRelationshipEdgeLlmGrounded(
  data: RelationshipEdgeData | undefined
): boolean | undefined {
  const grounded = data?.llmGrounded
  return typeof grounded === 'boolean' ? grounded : undefined
}

export interface CharacterNodeData {
  [k: string]: unknown
  name: string
  role?: string
  avatarUrl?: string
  description?: string
  type: 'character' | 'faction' | 'place' | 'event' | 'rule'
  // Metrics for visualization
  stressLevel?: number // 0-100
  transformationProgress?: number // 0-100
  // For highlighting
  isHighlighted?: boolean
  isCentral?: boolean
  /** Entity is the focused/navigated-to entity (cyan ring) */
  isSelected?: boolean
}

export interface RelationshipEdgeData {
  [k: string]: unknown
  relationshipType: RelationshipType
  strength: number // 0-1
  trust?: number // -1 to 1
  dynamic?: string
  /** Textual evidence from LLM extraction (story text quote/paraphrase) */
  evidence?: string
  /** True when this edge was generated by the LLM extractor (most accurate) */
  llmGrounded?: boolean
  history?: Array<{
    beatId: string
    change: string
  }>
}

// Node type for React Flow
export type CharacterWebNode = Node<CharacterNodeData>

// Edge type for React Flow
export type CharacterWebEdge = Edge<RelationshipEdgeData>

// Edge styling based on relationship type
export const RELATIONSHIP_STYLES: Record<
  RelationshipType,
  {
    color: string
    strokeStyle: string
    strokeWidth: number
    animated: boolean
  }
> = {
  ally: { color: '#22c55e', strokeStyle: 'solid', strokeWidth: 2, animated: false },
  enemy: { color: '#ef4444', strokeStyle: 'dashed', strokeWidth: 2, animated: true },
  rival: { color: '#f97316', strokeStyle: 'dotted', strokeWidth: 2, animated: false },
  mentor: { color: '#a855f7', strokeStyle: 'solid', strokeWidth: 3, animated: false },
  student: { color: '#a855f7', strokeStyle: 'solid', strokeWidth: 1, animated: false },
  lover: { color: '#ec4899', strokeStyle: 'solid', strokeWidth: 3, animated: true },
  family: { color: '#3b82f6', strokeStyle: 'solid', strokeWidth: 2, animated: false },
  member_of: { color: '#6366f1', strokeStyle: 'dashed', strokeWidth: 1, animated: false },
  leader_of: { color: '#6366f1', strokeStyle: 'solid', strokeWidth: 3, animated: false },
  associated: { color: '#94a3b8', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  related: { color: '#64748b', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  // Object / structural relationships
  owns: { color: '#f59e0b', strokeStyle: 'solid', strokeWidth: 1, animated: false },
  uses: { color: '#eab308', strokeStyle: 'dashed', strokeWidth: 1, animated: false },
  caused_by: { color: '#f43f5e', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  happened_at: { color: '#10b981', strokeStyle: 'solid', strokeWidth: 1, animated: false },
  located_in: { color: '#10b981', strokeStyle: 'dashed', strokeWidth: 1, animated: false },
  temporal: { color: '#8b5cf6', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  // Soft relationships
  stranger: { color: '#52525b', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  acquaintance: { color: '#71717a', strokeStyle: 'dotted', strokeWidth: 1, animated: false },
  complex: { color: '#fb923c', strokeStyle: 'dashed', strokeWidth: 2, animated: true },
}

// API response types
export interface RelationshipMatrixResponse {
  nodes: Array<{
    id: string
    name: string
    type: 'character' | 'faction' | 'place' | 'event' | 'rule'
    description?: string
    metadata: {
      role?: string
      archetype?: string
      description?: string
      metrics?: {
        perceivedStakes?: number
        transformation?: number
      }
      [key: string]: unknown
    }
  }>
  edges: Array<{
    source: string
    target: string
    weight: number
    type: string
    label?: string
    /** Textual evidence from LLM extraction */
    evidence?: string
    /** True when grounded by LLM extraction, not purely cosine similarity */
    llmGrounded?: boolean
  }>
  centralCharacter?: string
}
