export const LIQUID_CONTEXT_HOOK_ERROR = 'useLiquid must be used within a LiquidProvider'
export const LIQUID_GL_SCRIPTS_LOADED_LOG = 'LiquidGL scripts loaded globally.'
export const LIQUID_GL_INIT_FAILED_LOG = 'LiquidGL initialization failed:'
export const TURBULENT_BG_CANVAS_ID = 'turbulent-bg-canvas'
export const WEBGL_POWER_PREFERENCE_HIGH_PERFORMANCE = 'high-performance'
export const DOM_EVENT_RESIZE = 'resize'
