
import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { assets } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'
import { writeFile, mkdir } from 'fs/promises'
import path from 'path'
import { eq } from 'drizzle-orm'

// Helper to generate thumbnail for 3D models
async function generate3DThumbnail(modelPath: string, outputPath: string): Promise<void> {
    // Use @llm/three to render a simple thumbnail
    // For now, we'll create a placeholder - in production, you'd use Three.js server-side rendering
    // or trigger a background job to render the model
    const sharp = (await import('sharp')).default

    // Create a simple dark gray placeholder with 3D icon indicator
    const svg = `
    <svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
      <rect width="512" height="512" fill="#1a1a1a"/>
      <text x="50%" y="50%" text-anchor="middle" dy=".3em" fill="#666" font-size="48" font-family="Arial">
        3D Model
      </text>
    </svg>
  `

    await sharp(Buffer.from(svg))
        .png()
        .toFile(outputPath)
}

export async function POST(req: NextRequest) {
    try {
        const formData = await req.formData()
        const file = formData.get('file') as File
        const projectId = formData.get('projectId') as string
        const assetId = formData.get('assetId') as string | null
        const updateExisting = formData.get('updateExisting') === 'true'

        // We might want user_id. For now hardcode or extract from session if available.
        // The schema requires user_id. 
        // I'll try to get it from a header or assume a default dev user if Auth is not strict yet,
        // or pass it from client.
        // Let's check how other routes handle it.
        // For now I'll require it from client or use a placeholder.
        const userId = formData.get('userId') as string || '00000000-0000-0000-0000-000000000000'

        if (!file || !projectId) {
            return NextResponse.json({ error: 'Missing file or projectId' }, { status: 400 })
        }

        const buffer = Buffer.from(await file.arrayBuffer())
        const filename = file.name.replace(/\s+/g, '_') // Sanitize
        const isModel = filename.endsWith('.glb') || filename.endsWith('.gltf')
        const isImage = filename.match(/\.(jpg|jpeg|png|webp)$/i)

        if (!isModel && !isImage) {
            return NextResponse.json({ error: 'Invalid file type. Only GLB, GLTF, PNG, JPG, WEBP allowed.' }, { status: 400 })
        }

        // Save to public folder
        // struct: public/projects/[id]/assets/[filename]
        const uploadDir = path.join(process.cwd(), 'public', 'projects', projectId, 'assets')
        await mkdir(uploadDir, { recursive: true })

        const filePath = path.join(uploadDir, filename)
        await writeFile(filePath, buffer)

        // If updating an existing asset (e.g., adding 2D image to asset that only has 3D model)
        if (updateExisting && assetId && isImage) {
            // First get the existing asset to merge metadata
            const existingAsset = await db.select().from(assets).where(eq(assets.id, assetId)).limit(1)
            const existingMetadata = (existingAsset[0]?.metadata as Record<string, any>) || {}
            
            // Update image filename and clear autoGeneratedThumbnail flag
            await db.update(assets)
                .set({ 
                    imageFilename: filename,
                    metadata: {
                        ...existingMetadata,
                        autoGeneratedThumbnail: false,
                        originalImageName: file.name,
                        imageSize: file.size
                    }
                })
                .where(eq(assets.id, assetId))
            
            return NextResponse.json({ 
                success: true, 
                assetId: assetId, 
                filename,
                imageFilename: filename,
                updated: true
            })
        }

        // Generate thumbnail for 3D models
        let thumbnailFilename = 'placeholder.png'
        if (isModel) {
            thumbnailFilename = filename.replace(/\.(glb|gltf)$/i, '_thumb.png')
            const thumbnailPath = path.join(uploadDir, thumbnailFilename)
            await generate3DThumbnail(filePath, thumbnailPath)
        }

        // DB Insert
        // Asset: { id, project_id, user_id, image_filename, model_filename, ... }
        const newAsset = {
            id: uuidv4(),
            projectId,
            // If it's a model, we generate a thumbnail
            // If it's an image, use the image itself
            imageFilename: isImage ? filename : thumbnailFilename,
            modelFilename: isModel ? filename : null,
            metadata: {
                originalName: file.name,
                size: file.size,
                type: isModel ? 'model' : 'image',
                autoGeneratedThumbnail: isModel
            }
        }

        await db.insert(assets).values({
            id: newAsset.id,
            projectId: newAsset.projectId,
            userId: userId, // Using placeholder - should get from session in production
            imageFilename: newAsset.imageFilename,
            modelFilename: newAsset.modelFilename,
            metadata: newAsset.metadata,
        })

        return NextResponse.json({ success: true, assetId: newAsset.id, filename })
    } catch (error) {
        console.error('Upload failed:', error)
        return NextResponse.json({ error: 'Upload failed' }, { status: 500 })
    }
}
