import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/db/client'
import { assets, projects } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'
import { writeFile, mkdir } from 'fs/promises'
import path from 'path'
import { eq } from 'drizzle-orm'
import { requireAuth } from '@/shared/auth/auth'
import { formFile, formString } from '@/shared/data/form-data-guards'
import { recordFromJson } from '@/shared/data/json-guards'
import { API_ERROR, API_LOG_PREFIX } from '@/shared/data/constants/api-errors'
import {
  AssetMetadataType,
  AssetUploadFilename,
  AuthBypassFlag,
  FormField,
  FsDirectory,
  ModelFileExtension,
} from '@/shared/data/constants/protocol'

// Helper to generate thumbnail for 3D models
async function generate3DThumbnail(_modelPath: string, outputPath: string): Promise<void> {
  // Use @llm/three to render a simple thumbnail
  // For now, we'll create a placeholder - in production, you'd use Three.js server-side rendering
  // or trigger a background job to render the model
  const sharp = (await import('sharp')).default

  // Create a simple dark gray placeholder with 3D icon indicator
  const svg = `
    <svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
      <rect width="512" height="512" fill="#1a1a1a"/>
      <text x="50%" y="50%" text-anchor="middle" dy=".3em" fill="#666" font-size="48" font-family="Arial">
        3D Model
      </text>
    </svg>
  `

  await sharp(Buffer.from(svg)).png().toFile(outputPath)
}

export async function POST(req: NextRequest) {
  try {
    const { session } = await requireAuth()
    if (!session) {
      return NextResponse.json({ error: API_ERROR.UNAUTHORIZED }, { status: 401 })
    }

    const formData = await req.formData()
    const file = formFile(formData, FormField.File)
    const projectId = formString(formData, FormField.ProjectId)
    const assetId = formString(formData, FormField.AssetId)
    const updateExisting = formData.get(FormField.UpdateExisting) === AuthBypassFlag.True

    if (!file || !projectId) {
      return NextResponse.json({ error: API_ERROR.MISSING_FILE_OR_PROJECT_ID }, { status: 400 })
    }

    // Check ownership
    const [project] = await db.select().from(projects).where(eq(projects.id, projectId))
    if (!project || project.userId !== session.user.id) {
      return NextResponse.json({ error: API_ERROR.UNAUTHORIZED_ACCESS_TO_PROJECT }, { status: 403 })
    }

    const buffer = Buffer.from(await file.arrayBuffer())
    const filename = path.basename(file.name).replace(/\s+/g, '_') // Sanitize: strip directory components and spaces
    const isModel =
      filename.endsWith(ModelFileExtension.Glb) || filename.endsWith(ModelFileExtension.Gltf)
    const isImage = filename.match(/\.(jpg|jpeg|png|webp)$/i)

    if (!isModel && !isImage) {
      return NextResponse.json({ error: API_ERROR.INVALID_ASSET_FILE_TYPE }, { status: 400 })
    }

    // Save to public folder
    // struct: public/projects/[id]/assets/[filename]
    const uploadDir = path.join(
      process.cwd(),
      FsDirectory.Public,
      FsDirectory.Projects,
      projectId,
      FsDirectory.Assets
    )
    await mkdir(uploadDir, { recursive: true })

    const filePath = path.resolve(uploadDir, filename)
    if (!filePath.startsWith(uploadDir + path.sep) && filePath !== uploadDir) {
      return NextResponse.json({ error: API_ERROR.INVALID_FILENAME }, { status: 400 })
    }
    await writeFile(filePath, buffer)

    // If updating an existing asset (e.g., adding 2D image to asset that only has 3D model)
    if (updateExisting && assetId && isImage) {
      // First get the existing asset to merge metadata
      const existingAsset = await db.select().from(assets).where(eq(assets.id, assetId)).limit(1)
      const existingMetadata = recordFromJson(existingAsset[0]?.metadata)

      // Update image filename and clear autoGeneratedThumbnail flag
      await db
        .update(assets)
        .set({
          imageFilename: filename,
          metadata: {
            ...existingMetadata,
            autoGeneratedThumbnail: false,
            originalImageName: file.name,
            imageSize: file.size,
          },
        })
        .where(eq(assets.id, assetId))

      return NextResponse.json({
        success: true,
        assetId: assetId,
        filename,
        imageFilename: filename,
        updated: true,
      })
    }

    // Generate thumbnail for 3D models
    let thumbnailFilename: string = AssetUploadFilename.Placeholder
    if (isModel) {
      thumbnailFilename = filename.replace(/\.(glb|gltf)$/i, AssetUploadFilename.ThumbSuffix)
      const thumbnailPath = path.join(uploadDir, thumbnailFilename)
      await generate3DThumbnail(filePath, thumbnailPath)
    }

    // DB Insert
    // Asset: { id, project_id, user_id, image_filename, model_filename, ... }
    const newAsset = {
      id: uuidv4(),
      projectId,
      // If it's a model, we generate a thumbnail
      // If it's an image, use the image itself
      imageFilename: isImage ? filename : thumbnailFilename,
      modelFilename: isModel ? filename : null,
      metadata: {
        originalName: file.name,
        size: file.size,
        type: isModel ? AssetMetadataType.Model : AssetMetadataType.Image,
        autoGeneratedThumbnail: isModel,
      },
    }

    await db.insert(assets).values({
      id: newAsset.id,
      projectId: newAsset.projectId,
      userId: session.user.id,
      imageFilename: newAsset.imageFilename,
      modelFilename: newAsset.modelFilename,
      metadata: newAsset.metadata,
    })

    return NextResponse.json({ success: true, assetId: newAsset.id, filename })
  } catch (error) {
    console.error(API_LOG_PREFIX.ASSETS_UPLOAD_FAILED, error)
    return NextResponse.json({ error: API_ERROR.UPLOAD_FAILED }, { status: 500 })
  }
}
