import { NextResponse } from 'next/server'
import { db } from '@/db/client'
import { assets, projects } from '@/db/schema'
import { v4 as uuidv4 } from 'uuid'
import { writeFile, mkdir } from 'fs/promises'
import path from 'path'
import { eq } from 'drizzle-orm'
import { recordFromJson } from '@/shared/data/json-guards'
import { API_ERROR } from '@/shared/data/constants/api-errors'
import {
  AssetMetadataType,
  AssetUploadFilename,
  FsDirectory,
  ModelFileExtension,
} from '@/shared/data/constants/protocol'

export async function generate3DThumbnail(_modelPath: string, outputPath: string): Promise<void> {
  const sharp = (await import('sharp')).default

  const svg = `
    <svg width="512" height="512" xmlns="http://www.w3.org/2000/svg">
      <rect width="512" height="512" fill="#1a1a1a"/>
      <text x="50%" y="50%" text-anchor="middle" dy=".3em" fill="#666" font-size="48" font-family="Arial">
        3D Model
      </text>
    </svg>
  `

  await sharp(Buffer.from(svg)).png().toFile(outputPath)
}

interface UploadFileInfo {
  filename: string
  isModel: boolean
  isImage: boolean
}

export function parseUploadFileInfo(fileName: string): UploadFileInfo {
  const filename = path.basename(fileName).replace(/\s+/g, '_')
  const isModel =
    filename.endsWith(ModelFileExtension.Glb) || filename.endsWith(ModelFileExtension.Gltf)
  const isImage = !!filename.match(/\.(jpg|jpeg|png|webp)$/i)
  return { filename, isModel, isImage }
}

export function buildUploadDir(projectId: string): string {
  return path.join(
    process.cwd(),
    FsDirectory.Public,
    FsDirectory.Projects,
    projectId,
    FsDirectory.Assets
  )
}

export async function verifyProjectOwnership(
  projectId: string,
  userId: string
): Promise<NextResponse | null> {
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId))
  if (!project || project.userId !== userId) {
    return NextResponse.json({ error: API_ERROR.UNAUTHORIZED_ACCESS_TO_PROJECT }, { status: 403 })
  }
  return null
}

interface UpdateExistingAssetInput {
  assetId: string
  filename: string
  originalName: string
  fileSize: number
}

export async function updateExistingAssetImage(input: UpdateExistingAssetInput) {
  const existingAsset = await db
    .select()
    .from(assets)
    .where(eq(assets.id, input.assetId))
    .limit(1)
  const existingMetadata = recordFromJson(existingAsset[0]?.metadata)

  await db
    .update(assets)
    .set({
      imageFilename: input.filename,
      metadata: {
        ...existingMetadata,
        autoGeneratedThumbnail: false,
        originalImageName: input.originalName,
        imageSize: input.fileSize,
      },
    })
    .where(eq(assets.id, input.assetId))

  return NextResponse.json({
    success: true,
    assetId: input.assetId,
    filename: input.filename,
    imageFilename: input.filename,
    updated: true,
  })
}

interface CreateAssetInput {
  projectId: string
  userId: string
  filename: string
  originalName: string
  fileSize: number
  isModel: boolean
  isImage: boolean
  uploadDir: string
  filePath: string
}

export async function createNewAsset(input: CreateAssetInput) {
  let thumbnailFilename: string = AssetUploadFilename.Placeholder
  if (input.isModel) {
    thumbnailFilename = input.filename.replace(/\.(glb|gltf)$/i, AssetUploadFilename.ThumbSuffix)
    const thumbnailPath = path.join(input.uploadDir, thumbnailFilename)
    await generate3DThumbnail(input.filePath, thumbnailPath)
  }

  const newAsset = {
    id: uuidv4(),
    projectId: input.projectId,
    imageFilename: input.isImage ? input.filename : thumbnailFilename,
    modelFilename: input.isModel ? input.filename : null,
    metadata: {
      originalName: input.originalName,
      size: input.fileSize,
      type: input.isModel ? AssetMetadataType.Model : AssetMetadataType.Image,
      autoGeneratedThumbnail: input.isModel,
    },
  }

  await db.insert(assets).values({
    id: newAsset.id,
    projectId: newAsset.projectId,
    userId: input.userId,
    imageFilename: newAsset.imageFilename,
    modelFilename: newAsset.modelFilename,
    metadata: newAsset.metadata,
  })

  return NextResponse.json({ success: true, assetId: newAsset.id, filename: input.filename })
}

export function validateUploadPath(uploadDir: string, filePath: string): NextResponse | null {
  if (!filePath.startsWith(uploadDir + path.sep) && filePath !== uploadDir) {
    return NextResponse.json({ error: API_ERROR.INVALID_FILENAME }, { status: 400 })
  }
  return null
}

export async function saveUploadFile(uploadDir: string, filePath: string, buffer: Buffer) {
  await mkdir(uploadDir, { recursive: true })
  await writeFile(filePath, buffer)
}
