export const DEFAULT_FRAME_COLOR = '#7a6f5e'
export const OBJECT_COLOR_PRESET_WARM_TAUPE = DEFAULT_FRAME_COLOR
export const OBJECT_COLOR_PRESET_LIGHT_TAUPE = '#a39484'
export const OBJECT_COLOR_PRESET_DARK_TAUPE = '#5c534a'
export const OBJECT_COLOR_PRESET_WOOD = '#8b7355'
export const OBJECT_COLOR_PRESET_BROWN = '#6b5b4f'
export const OBJECT_COLOR_PRESET_CHARCOAL = '#3d3630'

export const OBJECT_COLOR_PRESETS = [
  OBJECT_COLOR_PRESET_WARM_TAUPE,
  OBJECT_COLOR_PRESET_LIGHT_TAUPE,
  OBJECT_COLOR_PRESET_DARK_TAUPE,
  OBJECT_COLOR_PRESET_WOOD,
  OBJECT_COLOR_PRESET_BROWN,
  OBJECT_COLOR_PRESET_CHARCOAL,
] as const
export const DOOR_HANDLE_COLOR = '#C0C0C0'
export const WINDOW_GLASS_COLOR = '#87CEEB'
export const DEFAULT_WALL_COLOR = '#e2e8f0'
export const TEXTURED_WALL_COLOR = '#ffffff'
export const FLOOR_DEFAULT_COLOR = '#94a3b8'
export const OBJECT_GHOST_PLACABLE_COLOR = '#f59e0b'
export const OBJECT_GHOST_BLOCKED_COLOR = '#ef4444'
export const OBJECT_SELECTION_COLOR = '#4f46e5'
export const PRIMITIVE_CUBE_COLOR = '#f59e0b'
export const PRIMITIVE_SPHERE_COLOR = '#10b981'
export const PRIMITIVE_CYLINDER_COLOR = '#ec4899'
export const PRIMITIVE_CONE_COLOR = '#8b5cf6'
export const DEMO_BUILDING_COLOR = '#71717a'
export const DEMO_BUILDING_ROOF_COLOR = '#3f3f46'
export const DEMO_TREE_TRUNK_COLOR = '#78350f'
export const DEMO_TREE_LEAF_COLOR = '#166534'
export const EXTERNAL_MODEL_ERROR_COLOR = '#ef4444'
export const TERRAIN_WALL_SIDE_COLOR = '#3d6b4a'
