export enum TileProgressStage {
  Initializing = 'initializing',
  AssemblingContext = 'assembling_context',
  GeneratingImage = 'generating_image',
  SubmittingApiframe = 'submitting_apiframe',
  WaitingApiframe = 'waiting_apiframe',
  DownloadingResult = 'downloading_result',
  UploadingVariants = 'uploading_variants',
  Uploading = 'uploading',
  PreparingVariants = 'preparing_variants',
  SubmittingUploadPaint = 'submitting_upload_paint',
  WaitingUploadPaint = 'waiting_upload_paint',
  SubmittingUpscale = 'submitting_upscale',
  WaitingUpscale = 'waiting_upscale',
  CheckingOriginal = 'checking_original',
  Enhancing = 'enhancing',
  PendingReview = 'pending_review',
  Completed = 'completed',
  WaitingVariantSelection = 'waiting_variant_selection',
  Unknown = 'unknown',
}

export enum TileProgressLabel {
  Init = 'Init',
  Context = 'Context',
  Generating = 'Generating',
  Uploading = 'Uploading',
  Variants = 'Variants',
  Submitting = 'Submitting',
  Apiframe = 'Apiframe…',
  Midjourney = 'MJ…',
  Upscaling = 'Upscaling',
  Enhancing = 'Enhancing',
  Review = 'Review',
  MidjourneyUpscale = 'MJ upscale…',
  Finishing = 'Finishing',
  Done = 'Done',
  Starting = 'Starting',
}

export const TILE_STAGE_LABELS: Record<string, TileProgressLabel> = {
  [TileProgressStage.Initializing]: TileProgressLabel.Init,
  [TileProgressStage.AssemblingContext]: TileProgressLabel.Context,
  [TileProgressStage.GeneratingImage]: TileProgressLabel.Generating,
  [TileProgressStage.SubmittingApiframe]: TileProgressLabel.Apiframe,
  [TileProgressStage.WaitingApiframe]: TileProgressLabel.Apiframe,
  [TileProgressStage.DownloadingResult]: TileProgressLabel.Finishing,
  [TileProgressStage.UploadingVariants]: TileProgressLabel.Uploading,
  [TileProgressStage.Uploading]: TileProgressLabel.Uploading,
  [TileProgressStage.PreparingVariants]: TileProgressLabel.Variants,
  [TileProgressStage.SubmittingUploadPaint]: TileProgressLabel.Submitting,
  [TileProgressStage.WaitingUploadPaint]: TileProgressLabel.Midjourney,
  [TileProgressStage.SubmittingUpscale]: TileProgressLabel.Upscaling,
  [TileProgressStage.WaitingUpscale]: TileProgressLabel.MidjourneyUpscale,
  [TileProgressStage.CheckingOriginal]: TileProgressLabel.Finishing,
  [TileProgressStage.Enhancing]: TileProgressLabel.Enhancing,
  [TileProgressStage.PendingReview]: TileProgressLabel.Review,
  [TileProgressStage.Completed]: TileProgressLabel.Done,
  [TileProgressStage.Unknown]: TileProgressLabel.Starting,
}

export const TILE_COORD_SEPARATOR = ','
