export const GENRE_METRIC_PRIORITIES: Record<string, string[]> = {
  'survivors-like': [
    'Core Loop Completion Rate',
    'Reward Frequency',
    'Sessions Per Day',
    'Loop Friction Score',
    'Day 1 Retention (D1)',
  ],
  roguelike: [
    'Time to First Win',
    'Build Diversity Index',
    'Day 7 Retention (D7)',
    'Meta-Loop Engagement',
    'Session Length',
  ],
  'deck-builder': [
    'Build Diversity Index',
    'Core Loop Completion Rate',
    'Day 7 Retention (D7)',
    'Time to First Win',
    'Meta-Loop Engagement',
  ],
  narrative: [
    'Session Length',
    'Completion Rate',
    'Review Score',
    'Day 30 Retention (D30)',
    'Churn Point',
  ],
  rpg: [
    'Session Length',
    'Meta-Loop Engagement',
    'Build Diversity Index',
    'Day 7 Retention (D7)',
    'Completion Rate',
  ],
  action: [
    'Core Loop Completion Rate',
    'Session Length',
    'Day 1 Retention (D1)',
    'Time to First Win',
    'Review Score',
  ],
  strategy: [
    'Session Length',
    'Day 7 Retention (D7)',
    'Day 30 Retention (D30)',
    'Build Diversity Index',
    'Review Score',
  ],
  casual: [
    'Day 1 Retention (D1)',
    'Sessions Per Day',
    'Core Loop Completion Rate',
    'LTV (Lifetime Value)',
    'Loop Friction Score',
  ],
  competitive: [
    'Sessions Per Day',
    'Day 30 Retention (D30)',
    'K-Factor',
    'ARPDAU (Average Revenue Per Daily Active User)',
    'Content Creator Coverage',
  ],
  mobile: [
    'Day 1 Retention (D1)',
    'Sessions Per Day',
    'ARPDAU (Average Revenue Per Daily Active User)',
    'Conversion Rate',
    'LTV (Lifetime Value)',
  ],
  f2p: [
    'Conversion Rate',
    'ARPDAU (Average Revenue Per Daily Active User)',
    'LTV (Lifetime Value)',
    'Day 7 Retention (D7)',
    'K-Factor',
  ],
  // Default fallback for unknown genres
  default: [
    'Day 1 Retention (D1)',
    'Day 7 Retention (D7)',
    'Session Length',
    'Core Loop Completion Rate',
    'Review Score',
  ],
}
