import type { GenreMarketData, SteamGameData } from './steam-trending-types'

export const STEAM_TOP_GAMES: SteamGameData[] = [
  {
    name: 'Counter-Strike 2',
    appId: 730,
    currentPlayers: 1200000,
    peakPlayers24h: 1450000,
    averagePlayers30d: 1100000,
    trend: 'stable',
    percentChange: 2.5,
    genre: ['FPS', 'Competitive', 'Tactical Shooter'],
    tags: ['competitive', 'esports', 'team-based', 'skill-based'],
    releaseDate: '2023-09-27',
    priceUSD: 'free',
    reviewScore: 85,
    isIndie: false,
  },
  {
    name: 'Dota 2',
    appId: 570,
    currentPlayers: 650000,
    peakPlayers24h: 850000,
    averagePlayers30d: 620000,
    trend: 'stable',
    percentChange: -1.2,
    genre: ['MOBA', 'Strategy', 'Competitive'],
    tags: ['competitive', 'esports', 'team-based', 'complex'],
    releaseDate: '2013-07-09',
    priceUSD: 'free',
    reviewScore: 82,
    isIndie: false,
  },
  {
    name: 'PUBG: BATTLEGROUNDS',
    appId: 578080,
    currentPlayers: 420000,
    peakPlayers24h: 550000,
    averagePlayers30d: 400000,
    trend: 'declining',
    percentChange: -8.5,
    genre: ['Battle Royale', 'Shooter'],
    tags: ['battle-royale', 'survival', 'multiplayer'],
    releaseDate: '2017-12-21',
    priceUSD: 'free',
    reviewScore: 65,
    isIndie: false,
  },
  {
    name: 'Elden Ring',
    appId: 1245620,
    currentPlayers: 85000,
    peakPlayers24h: 120000,
    averagePlayers30d: 95000,
    trend: 'rising',
    percentChange: 15.3,
    genre: ['Action RPG', 'Souls-like', 'Open World'],
    tags: ['difficult', 'exploration', 'rpg', 'dark-fantasy'],
    releaseDate: '2022-02-25',
    priceUSD: 59.99,
    reviewScore: 93,
    isIndie: false,
  },
  {
    name: 'Baldur\'s Gate 3',
    appId: 1086940,
    currentPlayers: 72000,
    peakPlayers24h: 98000,
    averagePlayers30d: 85000,
    trend: 'stable',
    percentChange: -3.2,
    genre: ['RPG', 'CRPG', 'Turn-Based'],
    tags: ['story-rich', 'choices-matter', 'co-op', 'fantasy'],
    releaseDate: '2023-08-03',
    priceUSD: 59.99,
    reviewScore: 96,
    isIndie: false,
  },
  {
    name: 'Vampire Survivors',
    appId: 1794680,
    currentPlayers: 25000,
    peakPlayers24h: 42000,
    averagePlayers30d: 28000,
    trend: 'stable',
    percentChange: 5.1,
    genre: ['Roguelike', 'Action', 'Bullet Hell'],
    tags: ['auto-battler', 'roguelite', 'casual', 'indie'],
    releaseDate: '2022-10-20',
    priceUSD: 4.99,
    reviewScore: 98,
    isIndie: true,
  },
  {
    name: 'Hades',
    appId: 1145360,
    currentPlayers: 18000,
    peakPlayers24h: 28000,
    averagePlayers30d: 20000,
    trend: 'rising',
    percentChange: 12.8,
    genre: ['Roguelike', 'Action', 'Hack and Slash'],
    tags: ['roguelite', 'story-rich', 'indie', 'mythological'],
    releaseDate: '2020-09-17',
    priceUSD: 24.99,
    reviewScore: 97,
    isIndie: true,
  },
  {
    name: 'Slay the Spire',
    appId: 646570,
    currentPlayers: 15000,
    peakPlayers24h: 22000,
    averagePlayers30d: 16000,
    trend: 'rising',
    percentChange: 8.5,
    genre: ['Roguelike', 'Deckbuilding', 'Strategy'],
    tags: ['roguelite', 'card-game', 'turn-based', 'indie'],
    releaseDate: '2019-01-23',
    priceUSD: 24.99,
    reviewScore: 97,
    isIndie: true,
  },
  {
    name: 'Dead Cells',
    appId: 588650,
    currentPlayers: 8500,
    peakPlayers24h: 14000,
    averagePlayers30d: 9500,
    trend: 'stable',
    percentChange: 2.1,
    genre: ['Roguelike', 'Metroidvania', 'Action'],
    tags: ['roguelite', 'action', 'indie', 'pixel-graphics'],
    releaseDate: '2018-08-07',
    priceUSD: 24.99,
    reviewScore: 95,
    isIndie: true,
  },
  {
    name: 'Lethal Company',
    appId: 1966720,
    currentPlayers: 45000,
    peakPlayers24h: 85000,
    averagePlayers30d: 55000,
    trend: 'rising',
    percentChange: 45.2,
    genre: ['Horror', 'Co-op', 'Social'],
    tags: ['co-op', 'horror', 'indie', 'multiplayer'],
    releaseDate: '2023-10-23',
    priceUSD: 9.99,
    reviewScore: 96,
    isIndie: true,
  },
  {
    name: 'Balatro',
    appId: 2379780,
    currentPlayers: 38000,
    peakPlayers24h: 65000,
    averagePlayers30d: 42000,
    trend: 'rising',
    percentChange: 85.3,
    genre: ['Roguelike', 'Deckbuilding', 'Poker'],
    tags: ['roguelite', 'card-game', 'indie', 'addictive'],
    releaseDate: '2024-02-20',
    priceUSD: 14.99,
    reviewScore: 98,
    isIndie: true,
  },
  {
    name: 'Palworld',
    appId: 1623730,
    currentPlayers: 65000,
    peakPlayers24h: 120000,
    averagePlayers30d: 85000,
    trend: 'declining',
    percentChange: -25.4,
    genre: ['Survival', 'Creature Collector', 'Open World'],
    tags: ['survival', 'crafting', 'co-op', 'early-access'],
    releaseDate: '2024-01-19',
    priceUSD: 29.99,
    reviewScore: 81,
    isIndie: true,
  },
  {
    name: 'Escape from Tarkov',
    currentPlayers: 85000,
    peakPlayers24h: 125000,
    averagePlayers30d: 90000,
    trend: 'rising',
    percentChange: 18.7,
    genre: ['Extraction Shooter', 'FPS', 'Survival'],
    tags: ['hardcore', 'tactical', 'loot', 'pvpve'],
    releaseDate: '2017-07-27',
    priceUSD: 44.99,
    reviewScore: 75,
    isIndie: false,
  },
  {
    name: 'Dark and Darker',
    currentPlayers: 42000,
    peakPlayers24h: 68000,
    averagePlayers30d: 45000,
    trend: 'rising',
    percentChange: 32.1,
    genre: ['Extraction', 'Dungeon Crawler', 'PvPvE'],
    tags: ['extraction', 'fantasy', 'co-op', 'pvp'],
    releaseDate: '2023-08-14',
    priceUSD: 'free',
    reviewScore: 72,
    isIndie: true,
  },
]

export const GENRE_MARKET_DATA: GenreMarketData[] = [
  {
    genre: 'Roguelike/Roguelite',
    totalPlayers: 180000,
    topGames: ['Hades', 'Vampire Survivors', 'Slay the Spire', 'Dead Cells', 'Balatro'],
    growthRate: '+23% YoY',
    marketShare: 4.5,
    trending: true,
    recentReleases: ['Balatro', 'Halls of Torment', 'Balatro DLC'],
  },
  {
    genre: 'Competitive FPS',
    totalPlayers: 2500000,
    topGames: ['Counter-Strike 2', 'Valorant', 'Apex Legends', 'Overwatch 2'],
    growthRate: '+5% YoY',
    marketShare: 18.2,
    trending: false,
    recentReleases: ['The Finals', 'XDefiant'],
  },
  {
    genre: 'Extraction Shooter',
    totalPlayers: 250000,
    topGames: ['Escape from Tarkov', 'Dark and Darker', 'Hunt: Showdown', 'The Cycle: Frontier'],
    growthRate: '+47% YoY',
    marketShare: 2.8,
    trending: true,
    recentReleases: ['Arena Breakout: Infinite', 'Gray Zone Warfare'],
  },
  {
    genre: 'Narrative RPG/CRPG',
    totalPlayers: 180000,
    topGames: ['Baldur\'s Gate 3', 'Disco Elysium', 'Pathfinder', 'Pillars of Eternity'],
    growthRate: '+15% YoY',
    marketShare: 3.2,
    trending: true,
    recentReleases: ['Baldur\'s Gate 3 Mods', 'Solasta Updates'],
  },
  {
    genre: 'Survivors-like',
    totalPlayers: 95000,
    topGames: ['Vampire Survivors', 'Balatro', 'Halls of Torment', '20 Minutes Till Dawn'],
    growthRate: '+35% YoY',
    marketShare: 1.5,
    trending: true,
    recentReleases: ['Deep Rock Galactic: Survivor', 'Soulstone Survivors'],
  },
  {
    genre: 'Cozy/Farming Sim',
    totalPlayers: 120000,
    topGames: ['Stardew Valley', 'Spiritfarer', 'My Time at Sandrock', 'Sun Haven'],
    growthRate: '+28% YoY',
    marketShare: 2.1,
    trending: true,
    recentReleases: ['Fields of Mistria', 'Coral Island 1.0'],
  },
  {
    genre: 'Horror Co-op',
    totalPlayers: 150000,
    topGames: ['Lethal Company', 'Phasmophobia', 'Content Warning', 'Devour'],
    growthRate: '+65% YoY',
    marketShare: 1.8,
    trending: true,
    recentReleases: ['Content Warning', 'Buckshot Roulette'],
  },
]
